import cv2                                       #pip install cv2
import numpy as np                               #pip install numpy
url = 'rtsp://192.168.43.145'                    #URL of the phone (Generally generated by ip cam app)
cap = cv2.VideoCapture(url)                      #Setting url as frames
while (True):
    ret, frame = cap.read()
    if frame is not None:
        cv2.imshow('frame',frame)
    q=cv2.waitKey(1)
    if q == ord("q"):
        break
cv2.destroyAllWindows()
